### ISSUE TITLE
I receving error for compile 

### ISSUE THREAD

**Issue by recondiscord** [Lunaerix/LunaBot#62]
![image](https://cloud.githubusercontent.com/assets/24801374/21644651/a08d419c-d275-11e6-8591-c53af8db47e5.png)

**Comment by Lunaerix** [comment]
Hmm.. First guess would be something wrong with the client / secret ids
from Reddit. That 401 is likely coming from a failed login attempt. Double
check that you've copied them properly from Reddit into the bot global
configuration file.

Worst case scenario, if time is of the essence and you have no need of the
Reddit functionality, remove the Reddit module file and comment out its
load statement in the main file and it should build just fine. I can
investigate this more in detail later.

Additionally, your image shows the secret token, password, etc. I would
recommend regenerating those, as you should be the only person who knows
them.

**Comment by recondiscord** [comment]
Do you have discordapp ?, lately I do not have much time, to be able to solve this, but I am very interested in hostear your bot, just need a functional build, I would send my apis to you, is that really these times I am very busy

**Comment by recondiscord** [comment]
My server discordapp https://discord.gg/az3cnR2 and my nick is BinaryPony

**Comment by Lunaerix** [comment]
Resolved in #64.
