### ISSUE TITLE
I removed Reddit

### ISSUE THREAD

**Issue by recondiscord** [Lunaerix/LunaBot#64]
I really need remove reddit agent for my case is impossible for get URI functional, but bot run normally wighout this

**Comment by recondiscord** [comment]
![image](https://cloud.githubusercontent.com/assets/24801374/21660587/22c6aff4-d2b7-11e6-865d-f2188f8b5416.png)
![image](https://cloud.githubusercontent.com/assets/24801374/21660594/26728600-d2b7-11e6-9fd6-cbbf01cb40b6.png)

**Comment by Lunaerix** [comment]
Glad you got things resolved. All of the modules are exactly that - modules - so feel free to remove anything you don't need.
